data:
  mongodb:
    uri: mongodb://localhost:27017/chatdb

  web:
    resources:
      add-mappings: true

server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
